name: Total3D
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - certifi=2020.6.20
  - cffi=1.14.0
  - cudatoolkit=9.0
  - curl=7.69.1
  - expat=2.2.6
  - freetype=2.9.1
  - future=0.18.2
  - geos=3.8.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icu=58.2
  - intel-openmp=2020.1
  - jpeg=9b
  - jsoncpp=1.8.4
  - krb5=1.17.1
  - ld_impl_linux-64=2.33.1
  - libcurl=7.69.1
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libnetcdf=4.6.1
  - libogg=1.3.2
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtheora=1.1.1
  - libtiff=4.1.0
  - libvorbis=1.3.6
  - libxml2=2.9.10
  - lz4-c=1.8.1.2
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1g
  - pandas=1.0.5
  - pillow=7.1.2
  - pip=20.0.2
  - pycparser=2.20
  - python=3.6.10
  - python-dateutil=2.8.1
  - pytorch=1.1.0
  - pytz=2020.1
  - pyyaml=5.3.1
  - readline=8.0
  - scipy=1.4.1
  - setuptools=47.1.1
  - shapely=1.7.0
  - six=1.15.0
  - sqlite=3.31.1
  - tbb=2020.0
  - tk=8.6.8
  - torchvision=0.3.0
  - vtk=8.2.0
  - wheel=0.34.2
  - xz=5.2.5
  - yaml=0.1.7
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - cycler==0.10.0
    - jellyfish==0.8.2
    - kiwisolver==1.2.0
    - matplotlib==3.2.2
    - opencv-python==4.2.0.34
    - pyparsing==2.4.7
    - seaborn==0.10.1

